name: Azure Data Factory

on:
  push:
    paths:
      - 'ADFIntegration/**'
      - '**/AzureDataFactory.yml'
    branches:
    - dev
    - main

env:
  folderwithpackagedotjsonfile: ADFIntegration/DevOpsFiles
  subscription: d33e1d84-2e9a-471b-be9c-560633380015
  resourceGroup: ADF
  dataFactory: adfgithubactions

jobs:
  Build:
    name: Build Stage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install npm package
      working-directory: ${{ github.workspace }}/${{ env.folderwithpackagedotjsonfile  }}
      run: npm install
    - name: Validate
      working-directory: ${{ github.workspace }}/${{ env.folderwithpackagedotjsonfile  }} 
      run: npm run build validate ${{ github.workspace }}/ADFIntegration /subscriptions/${{ env.subscription  }}/resourceGroups/${{ env.resourceGroup  }}/providers/Microsoft.DataFactory/factories/${{ env.dataFactory  }} ${{ github.workspace }}/${{ env.folderwithpackagedotjsonfile  }}
    - name: Generate ARM template
      working-directory: ${{ github.workspace }}/${{ env.folderwithpackagedotjsonfile  }} 
      run: npm run build export ${{ github.workspace }}/ADFIntegration /subscriptions/${{ env.subscription  }}/resourceGroups/${{ env.resourceGroup  }}/providers/Microsoft.DataFactory/factories/${{ env.dataFactory  }} "ArmTemplates" ${{ github.workspace }}/${{ env.folderwithpackagedotjsonfile  }}
    - uses: actions/upload-artifact@v2
      with:
        name: ArmTemplates
        path: ${{ github.workspace }}/ADFIntegration/DevOpsFiles/ArmTemplates
  DeployDev:
      needs: [Build]
      name: Dev Deploy
      runs-on: ubuntu-latest
      environment:
        name: Dev
      if: (github.ref ==  'refs/heads/dev') #please update the branch name here, variables in env are not accessible here
      steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_SPN }}
      - name: 'Download Pipeline Artifact: drop'
        uses: actions/download-artifact@v2
        with:
          name: ArmTemplates
          path: ArmTemplates
      - name: Stop trigger
        uses: azure/powershell@v1
        with:
          inlineScript: ./ArmTemplates/PrePostDeploymentScript.ps1 -armTemplate "ArmTemplates/ARMTemplateForFactory.json" -ResourceGroupName ${{ secrets.RESOURCEGROUP  }} -DataFactoryName ${{ secrets.DATAFACTORY  }} -predeployment $true -deleteDeployment $false
          azPSVersion: latest      
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.RESOURCEGROUP }}
          template: ./ArmTemplates/ARMTemplateForFactory.json
          parameters: ./ArmTemplates/ARMTemplateParametersDev.json
      - name: Start triggers
        uses: azure/powershell@v1
        with:
          inlineScript: ./ArmTemplates/PrePostDeploymentScript.ps1 -armTemplate "ArmTemplates/ARMTemplateForFactory.json" -ResourceGroupName ${{ secrets.RESOURCEGROUP  }} -DataFactoryName ${{ secrets.DATAFACTORY  }} -predeployment $false -deleteDeployment $false
          azPSVersion: latest
    
