name: Azure Sql Db

on:
  push:
    paths:
      - 'SqlProject/**'
      - '**/AzureSQLDb.yml'
    branches:
    - dev
    - main

env:
  projectName: TestDb
  
jobs:
  Build:
    name: Build Stage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Build solution SqlProject/${{ env.projectName  }}/${{ env.projectName  }}.sqlproj
      run: msbuild '${{ github.workspace }}/SqlProject/${{ env.projectName  }}/${{ env.projectName  }}.sqlproj    ' /t:build /p:CmdLineInMemoryStorage=True
    - name: 'Copy Files to: ${{ github.workspace }}'
      run: Copy '${{ github.workspace }}/SqlProject/${{ env.projectName  }}/bin/debug/' '${{ github.workspace }}'
    - name: 'Copy Files to: ${{ github.workspace }} copy'
      run: Copy '${{ github.workspace }}/SqlProject/${{ env.projectName  }}/${{ env.projectName  }}.publish.xml' '${{ github.workspace }}'
    - name: 'Publish Artifact: drop'
      uses: actions/upload-artifact@v2
      with:
        name: SqlProject
    