name: CI CD
on:
  push:
    branches:
    - main
    - dev
env:
  devBranch: refs/heads/dev
  prodBranch: refs/heads/main
jobs:
  Build:
    name: Build Job
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ${{ github.workspace }}/notebooks/Shared/
        name: drop
  DeployDev:
    needs: [Build]
    name: DEV Deployment
    runs-on: windows-latest
    environment:
      name: Dev
    if: (github.ref == $devBranch)
    steps:
    - 
      run: |
        echo "Dev Deployment"
  DeployProd:
    name: Prod Deployment
    runs-on: windows-latest
    environment:
      name: Prod
    if: (github.ref == $prodBranch)
    steps:
    - 
      run: |
        echo "Prod Deployment"
