name: CI CD
on:
  push:
    branches:
    - main
    paths:
    - notebooks
jobs:
  Build:
    name: Build Job
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ${{ github.workspace }}/notebooks/Shared/
        name: drop
