name: CI CD

on:
  push:
    branches:
    - main
    - dev
    
env:
  DEV_BRANCH: refs/heads/dev
  PROD_BRANCH: refs/heads/main
  
jobs:
  Build:
    name: Build Job
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ${{ github.workspace }}/notebooks/Shared/
        name: drop
  DeployDev:
    needs: [Build]
    name: DEV Deployment
    runs-on: windows-latest
    environment:
      name: Dev   
    steps:
    - name: Dev Steps
      if: (github.ref == '${{ env.DEV_BRANCH  }}')
      run: |
        echo "Dev Deployment"
  DeployProd:
    needs: [DeployDev]
    name: Prod Deployment
    runs-on: windows-latest
    environment:
      name: Prod  
    steps:
    - name: Prod Steps
      if: (github.ref == '${{ env.PROD_BRANCH  }}')
      run: |
        echo "PROD Deployment"
