name: Data Bricks

on:
  push:
    branches:
    - main
    - dev
  
jobs:
  Build:
    name: Build Job
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ${{ github.workspace }}/notebooks/Shared/
        name: drop
  DeployDev:
    needs: [Build]
    name: DEV Deployment
    runs-on: windows-latest
    environment:
      name: Dev
    if: (github.ref ==  'refs/heads/dev') #please update the branch name here, variables in env are not accessible here
    steps:
    - name: install Databrick CLI
      uses: microsoft/install-databricks-cli@v1.0.0
    - name: Upload Databricks
      uses: microsoft/databricks-import-notebook@v1.0.0
      with:
        databricks-host: $DATABRICKSHOST
        databricks-token: $TOKEN
        local-path: ./
        remote-path: $REMOTEPATH
  DeployProd:
    needs: [Build]
    name: Prod Deployment
    runs-on: windows-latest
    environment:
      name: Prod
    if: (github.ref ==  'refs/heads/main') #please update the branch name here, variables in env are not accessible here  
    steps:
    - name: install Databrick CLI
      uses: microsoft/install-databricks-cli@v1.0.0
    - name: Upload Databricks
      uses: microsoft/databricks-import-notebook@v1.0.0
      with:
        databricks-host: $DATABRICKSHOST
        databricks-token: $TOKEN
        local-path: ./
        remote-path: $REMOTEPATH
